### PR TITLE
Add unit test github action. Run as non-root uid. Install python packages in virtualenv.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by marcpaterno** [comment]
I again confused by the check output above. The list seems to indicate that several things have failed (e.g. the unit tests under Python 2.7). But when I look at the details link, I can't find anything that actually did fail, nor do I see evidence that any unit tests were run. There is plenty of output from the build (I think way more than needed), but I do not see what caused the failure.

We need to give some thought to how to clean up the output so that (1) successful tests are pretty quiet and (2) tests that fail make it clear exactly what has failed.

**Comment by gartung** [comment]
The output of pytest is output to a log and archived in the test-log artifact.

**Comment by gartung** [comment]
click https://github.com/HEPCloud/decisionengine_modules/actions/runs/54436167
click artifacts
In safari click on the down arrow icon, select the test-log folder and open it in Finder then double click on the log name.

**Comment by marcpaterno** [comment]
I would much prefer to see a simpler process to find out what has failed. Most of the contents of https://github.com/HEPCloud/decisionengine_modules/pull/14/checks?check_run_id=503566735 seems to be items we do not need to see on a successful build. The output of the testing (currently written to the log) is what we really want to be able to see easily. I'd prefer to see that in the detail link, rather than what we're seeing now.

**Comment by gartung** [comment]
I now tee the output to the log so there are two places to find the pytest output.

**Pull request merged**
